# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 420)
        Form.setStyleSheet("QWidget#Form{border-image:url(:/img/qrc/guowang.jpg); }\n"
"\n"
"\n"
"QLabel#titleLabel{font: 15pt \"华文中宋\";}\n"
"QLabel#usernameLabel{color:rgb(255, 255, 255);}\n"
"\n"
"QLabel#passwordLabel{color:rgb(255, 255, 255);}\n"
"QLabel#returnMsg{font: 15pt;color:rgb(255, 255, 255);}\n"
"\n"
"")
        self.usernameLabel = QtWidgets.QLabel(Form)
        self.usernameLabel.setGeometry(QtCore.QRect(140, 170, 54, 12))
        self.usernameLabel.setObjectName("usernameLabel")
        self.userNameEdit = QtWidgets.QLineEdit(Form)
        self.userNameEdit.setGeometry(QtCore.QRect(200, 170, 191, 20))
        self.userNameEdit.setObjectName("userNameEdit")
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setGeometry(QtCore.QRect(140, 230, 54, 12))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(200, 230, 191, 20))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.pushButtonLogin = QtWidgets.QPushButton(Form)
        self.pushButtonLogin.setGeometry(QtCore.QRect(150, 300, 71, 31))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(Form)
        self.pushButtonExit.setGeometry(QtCore.QRect(280, 300, 70, 30))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.returnMsg = QtWidgets.QLabel(Form)
        self.returnMsg.setGeometry(QtCore.QRect(130, 350, 241, 31))
        self.returnMsg.setObjectName("returnMsg")
        self.titleLabel = QtWidgets.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(160, 30, 311, 20))
        self.titleLabel.setObjectName("titleLabel")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(140, 200, 251, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.closecontrolButton = QtWidgets.QPushButton(Form)
        self.closecontrolButton.setGeometry(QtCore.QRect(400, 300, 70, 30))
        self.closecontrolButton.setObjectName("closecontrolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usernameLabel.setText(_translate("Form", "用户名："))
        self.passwordLabel.setText(_translate("Form", "密码："))
        self.pushButtonLogin.setText(_translate("Form", "登录"))
        self.pushButtonExit.setText(_translate("Form", "退出"))
        self.returnMsg.setText(_translate("Form", "returnMsg"))
        self.titleLabel.setText(_translate("Form", "智能可视化监控设备蓄电池检测"))
        self.closecontrolButton.setText(_translate("Form", "断开连接"))
import guowang_rc
